# 2. URL JSON-LD souborů ke stažení podle OFN Turistické cíle
# Datasource: https://dev.nkod.opendata.cz/ldf/*
SELECT ?odkazKeStažení
WHERE {
  ?datová_sada a dcat:Dataset ;
    dcterms:conformsTo <https://ofn.gov.cz/turistické-cíle/2020-07-01/> ;
    dcat:distribution ?distribuce .

  ?distribuce a dcat:Distribution ;
    dcterms:format <http://publications.europa.eu/resource/authority/file-type/JSON_LD> ;
    dcat:downloadURL ?odkazKeStažení .
}